name: MSVC C/C++ CI

on: [push]

jobs:
  build:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: 'recursive'
          fetch-depth: 1

      - name: 编译
        uses: lukka/run-cmake@v3
        with:
          useVcpkgToolchainFile: true
          buildDirectory: '${{github.workspace}}/build'
          cmakeAppendedArgs: ''
          cmakeBuildType: 'RelWithDebInfo'
